### ISSUE TITLE
InvalidArgumentException with message 'Height value for portrait resize is empty. This may be caused by unfixed EXIF-rotated images'

### ISSUE THREAD

**Issue by flyingL123** [czim/laravel-paperclip#34]
I'm receiving the following error trying to save a photo with variants:

```
InvalidArgumentException with message 'Height value for portrait resize is empty. This may be caused by unfixed EXIF-rotated images'
```

This is my model set up:

```
$this->hasAttachedFile('image', [
	'variants' => [
			Variant::make('thumbnail')->steps([
					AutoOrientStep::make(),
					ResizeStep::make()->width(300),
			]),

			Variant::make('zoom')->steps([
					AutoOrientStep::make(),
					ResizeStep::make()->width(1280)->convertOptions(['quality' => 100]),
			]),
	],
]);
```
This is the image I am trying to save with variants when I receive the error:

https://s3.amazonaws.com/storeyourboard/App/CustomerPhoto/000/000/014/image/original/image_82432486101421854469.jpg

I have no clue what this error means. Can you explain?

**Comment by czim** [comment]
First off, I'm not sure that dimensions `300` is syntactically the same as setting `->width(300)`. Isn't dimensions `300` the same as `300x300`? This is besides the point for this particular error, but it may be relevant to your use case. If so, try using `->square(300)` instead.

As for the error, this is due to the `auto-orient` step being applied _after_ the resize step. This is a bug in Paperclip that I will fix.

**Comment by kimchirichie** [comment]
having an issue too. (without `AutoOrientStep`)

```
        $this->hasAttachedFile('image', [
            'variants'  => [
                Variant::make('thumb')->steps([
                    ResizeStep::make()->width(480)->height(270)->crop(), // = '480x270#'
                ]),
                Variant::make('small')->steps([
                    ResizeStep::make()->width(480), // = '480x'
                ]),
                Variant::make('medium')->steps([
                    ResizeStep::make()->width(640), // = '640x'
                ]),
                Variant::make('large')->steps([
                    ResizeStep::make()->width(1280), // = '1280x'
                ]),
            ],
            'url' => config('services.cdn.image_not_found'),
        ]);
```
thumb works, but others are not working.

Logging from `namespace Czim\Paperclip\Attachment\Attachment.php; L#789` gives:
```
[2020-10-15 04:31:37] local.DEBUG: InvalidArgumentException: Height value for portrait resize is empty. This may be caused by unfixed EXIF-rotated images in /Users/brainfogz/Documents/GitHub/oap/vendor/czim/file-handling/src/Support/Image/Resizer.php:219
```

seems to be an issue with the height being a variable? the lack of documentation really hinders me from being able to resolve this on my own. reaching for help!

**Comment by czim** [comment]
I've found and corrected an issue with the `file-handling` package. It turned out that `->width(<something>)` was internally rendered as dimensions string `<something>x` (with the `x` included), which was incorrectly interpreted by the resize logic as matching the 'portrait' resize approach (when it should be 'landscape', since it's width-based.

This has been fixed in `czim/file-handling` version `2.0.2`. If  you're using the newest version of paperclip, you should be able to `composer update` it. Please let me know if this resolves your issue.

**Comment by kimchirichie** [comment]
amazing. thanks for reopening this! this issues been on my mind all of last week. just got to try it out and got a different error this time!

Here is the stack trace:
`
[2020-10-20 06:08:38] local.DEBUG: ErrorException: A non well formed numeric value encountered in /Users/brainfogz/Documents/GitHub/oap/vendor/czim/file-handling/src/Support/Image/Resizer.php:304
Stack trace:
#0 /Users/brainfogz/Documents/GitHub/oap/vendor/czim/file-handling/src/Support/Image/Resizer.php(304): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'A non well form...', '/Users/brainfog...', 304, Array)
#1 /Users/brainfogz/Documents/GitHub/oap/vendor/czim/file-handling/src/Support/Image/Resizer.php(197): Czim\FileHandling\Support\Image\Resizer->getSizeByFixedWidth(Object(Imagine\Gd\Image), '480x')
#2 /Users/brainfogz/Documents/GitHub/oap/vendor/czim/file-handling/src/Support/Image/Resizer.php(60): Czim\FileHandling\Support\Image\Resizer->resizeLandscape(Object(Imagine\Gd\Image), '480x', NULL)
#3 /Users/brainfogz/Documents/GitHub/oap/vendor/czim/file-handling/src/Variant/Strategies/ImageResizeStrategy.php(34): Czim\FileHandling\Support\Image\Resizer->resize(Object(SplFileInfo), Array)
#4 /Users/brainfogz/Documents/GitHub/oap/vendor/czim/file-handling/src/Variant/Strategies/AbstractVariantStrategy.php(40): Czim\FileHandling\Variant\Strategies\ImageResizeStrategy->perform()
#5 /Users/brainfogz/Documents/GitHub/oap/vendor/czim/file-handling/src/Variant/VariantProcessor.php(121): Czim\FileHandling\Variant\Strategies\AbstractVariantStrategy->apply(Object(Czim\FileHandling\Storage\File\ProcessableFile))
#6 /Users/brainfogz/Documents/GitHub/oap/vendor/czim/file-handling/src/Handler/FileHandler.php(98): Czim\FileHandling\Variant\VariantProcessor->process(Object(Czim\FileHandling\Storage\File\SplFileInfoStorableFile), 'small', Array)
#7 /Users/brainfogz/Documents/GitHub/oap/vendor/czim/laravel-paperclip/src/Attachment/Attachment.php(786): Czim\FileHandling\Handler\FileHandler->processVariant(Object(Czim\FileHandling\Storage\File\SplFileInfoStorableFile), Object(Czim\Paperclip\Path\InterpolatingTarget), 'small', Array)
#8 /Users/brainfogz/Documents/GitHub/oap/vendor/czim/laravel-paperclip/src/Attachment/Attachment.php(341): Czim\Paperclip\Attachment\Attachment->processSingleVariant(Object(Czim\FileHandling\Storage\File\SplFileInfoStorableFile), 'small', Array)
#9 /Users/brainfogz/Documents/GitHub/oap/vendor/czim/laravel-paperclip/src/Console/Commands/RefreshAttachmentCommand.php(95): Czim\Paperclip\Attachment\Attachment->reprocess()
#10 /Users/brainfogz/Documents/GitHub/oap/vendor/czim/laravel-paperclip/src/Console/Commands/RefreshAttachmentCommand.php(59): Czim\Paperclip\Console\Commands\RefreshAttachmentCommand->processAttachmentOnModelInstance(Object(App\Photo), Object(Czim\Paperclip\Attachment\Attachment))
#11 [internal function]: Czim\Paperclip\Console\Commands\RefreshAttachmentCommand->handle()
#12 /Users/brainfogz/Documents/GitHub/oap/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array(Array, Array)
#13 /Users/brainfogz/Documents/GitHub/oap/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#14 /Users/brainfogz/Documents/GitHub/oap/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#15 /Users/brainfogz/Documents/GitHub/oap/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#16 /Users/brainfogz/Documents/GitHub/oap/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#17 /Users/brainfogz/Documents/GitHub/oap/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array)
#18 /Users/brainfogz/Documents/GitHub/oap/vendor/symfony/console/Command/Command.php(258): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#19 /Users/brainfogz/Documents/GitHub/oap/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#20 /Users/brainfogz/Documents/GitHub/oap/vendor/symfony/console/Application.php(920): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /Users/brainfogz/Documents/GitHub/oap/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand(Object(Czim\Paperclip\Console\Commands\RefreshAttachmentCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /Users/brainfogz/Documents/GitHub/oap/vendor/symfony/console/Application.php(142): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /Users/brainfogz/Documents/GitHub/oap/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /Users/brainfogz/Documents/GitHub/oap/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /Users/brainfogz/Documents/GitHub/oap/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 {main}  
`

It seems like `480x` is a non well formed numeric value. i will dig thru `file-handling` and see if i can find anything.

**Comment by kimchirichie** [comment]
upon inspection, the `Resizer::parseOptionDimensions` had returned `480x` instead of `480`. I've made a [PR](https://github.com/czim/file-handling/pull/10/files) and that seems to fix the issue on my end.

This issue is irrelevant to `czim/laravel-paperclip` and more pertinent to `czim/file-handling`. should close this issue.

**Comment by czim** [comment]
file-handling `2.0.3` should fix the issue now.
