### ISSUE TITLE
 Failed to reprocess attachment

### ISSUE THREAD

**Issue by rbruhn** [czim/laravel-paperclip#43]
Using latest Homestead I'm getting this error when trying to refresh. Any idea what might be causing it? I see the file it says it can't open in the /tmp directory. The owner/group is vagrant. Would appreciate any ideas on what is causing this.
```
[2019-07-24 21:13:40] local.ERROR: Failed to reprocess attachment 'logo' of App\Models\Expedition #17: Failed to process variant 'medium': Unable to open image /tmp/filehandling-variant-5d38ca04591ee.jpg {"exception":"[object] (Czim\\Paperclip\\Exceptions\\ReprocessingFailureException(code: 0): Failed to reprocess attachment 'logo' of App\\Models\\Expedition #17: Failed to process variant 'medium': Unable to open image /tmp/filehandling-variant-5d38ca04591ee.jpg at /home/vagrant/sites/biospexProd/vendor/czim/laravel-paperclip/src/Console/Commands/RefreshAttachmentCommand.php:81, Czim\\Paperclip\\Exceptions\\VariantProcessFailureException(code: 0): Failed to process variant 'medium': Unable to open image /tmp/filehandling-variant-5d38ca04591ee.jpg at /home/vagrant/sites/biospexProd/vendor/czim/laravel-paperclip/src/Attachment/Attachment.php:733, Imagine\\Exception\\RuntimeException(code: 0): Unable to open image /tmp/filehandling-variant-5d38ca04591ee.jpg at /home/vagrant/sites/biospexProd/vendor/imagine/imagine/lib/Imagine/Gd/Imagine.php:96)
[stacktrace]
#0 /home/vagrant/sites/biospexProd/vendor/czim/laravel-paperclip/src/Console/Commands/RefreshAttachmentCommand.php(57): Czim\\Paperclip\\Console\\Commands\\RefreshAttachmentCommand->processAttachmentOnModelInstance(Object(App\\Models\\Expedition), Object(Czim\\Paperclip\\Attachment\\Attachment))
#1 [internal function]: Czim\\Paperclip\\Console\\Commands\\RefreshAttachmentCommand->handle()
#2 /home/vagrant/sites/biospexProd/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#3 /home/vagrant/sites/biospexProd/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /home/vagrant/sites/biospexProd/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#5 /home/vagrant/sites/biospexProd/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#6 /home/vagrant/sites/biospexProd/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#7 /home/vagrant/sites/biospexProd/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#8 /home/vagrant/sites/biospexProd/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#9 /home/vagrant/sites/biospexProd/vendor/symfony/console/Application.php(921): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#10 /home/vagrant/sites/biospexProd/vendor/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand(Object(Czim\\Paperclip\\Console\\Commands\\RefreshAttachmentCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#11 /home/vagrant/sites/biospexProd/vendor/symfony/console/Application.php(149): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#12 /home/vagrant/sites/biospexProd/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 /home/vagrant/sites/biospexProd/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(133): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 /home/vagrant/sites/biospexProd/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 {main}
"} 
```

**Comment by czim** [comment]
This can happen when an original image is not available upon trying to reprocess it. Say an image does not exist in S3, and when trying to download it in order to reprocess it locally, it stores the 304 response HTML from S3, which can then not be processed as an image.

Or, when an image cannot be downloaded entirely, the tmp file does not exist and this error can occur.

The exception stack trace appears to be only for the 'outer' exception. Do you have the previous exception messages & traces as well, if there are any?
